name: TpaEchanted
version: '1.0-SNAPSHOT'
main: xyz.defesio.tpaechanted.TpaEchanted
api-version: 1.20
commands:
  tpa:
    description: Request teleport to a player
    usage: /<command> <player>
    permission: tpaechanted.tpa
    aliases: [tpa]
  tpaaccept:
    description: Accept a teleport request
    usage: /<command> <player>
    permission: tpaechanted.tpaaccept
    aliases: [tpaaccept] [tpaa]
